<a href="https://colab.research.google.com/github/ladeiraA/Lab_BigData/blob/main/Atividade2Naive.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [57]:
import pandas as pd
from sklearn.impute import SimpleImputer
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score

In [58]:
#base = arquivo
base = pd.read_csv("credit-data.csv")

In [59]:
#Ve valores negativos
baseA = base.loc[(base['age']) < 0]
baseA

i#clientid        income        age         loan  c#default
15          16  50501.726689 -28.218361  3977.287432          0
21          22  32197.620701 -52.423280  4244.057136          0
26          27  63287.038908 -36.496976  9595.286289          0

In [60]:
#Media
media = base.loc[:,'age'].mean()
media

40.80755937840458

In [61]:
#Transforma valores negativos na media do age
base.loc[base.age < 0,'age'] = media

In [62]:
#Mostrar que funcionou
base[15:27]

i#clientid        income        age         loan  c#default
15          16  50501.726689  40.807559  3977.287432          0
16          17  43548.654711  39.574530  3935.544453          0
17          18  43378.175194  60.848318  3277.737553          0
18          19  20542.365073  61.690571  3157.442290          0
19          20  58887.357549  26.076093  4965.516066          0
20          21  23000.784002  31.761354  1148.118057          0
21          22  32197.620701  40.807559  4244.057136          0
22          23  23329.319414  48.576975   222.622299          0
23          24  27845.800894  51.970624  4959.921226          0
24          25  65301.984029  48.840922  5465.267886          0
25          26  47451.630123  27.031741  5361.282716          0
26          27  63287.038908  40.807559  9595.286289          0

In [63]:
# imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
# data = [[12, np.nan, 34], [10, 32, np.nan], [np.nan, 11, 20]]
# print("Original data : \n", data)
# imputer = imputer.fit(data)
# data = imputer.transform(data)
# print("Imputed Data : \n", data)

In [64]:
previsores = base.iloc[:,1:4].values
previsores[25:32]
classe = base.iloc[:,4].values

In [65]:
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer = imputer.fit(previsores)
previsores = imputer.transform(previsores)
previsores[25:32]

array([[4.74516301e+04, 2.70317413e+01, 5.36128272e+03],
       [6.32870389e+04, 4.08075594e+01, 9.59528629e+03],
       [4.57274599e+04, 5.58399218e+01, 6.37682295e+03],
       [5.94178054e+04, 4.09275200e+01, 2.08262594e+03],
       [5.88428913e+04, 5.45109476e+01, 1.08711868e+04],
       [4.85288528e+04, 4.09275200e+01, 6.15578467e+03],
       [2.35263026e+04, 4.09275200e+01, 2.86201014e+03]])

In [66]:
scaler = StandardScaler()
previsores = scaler.fit_transform(previsores)
previsores[25:32]

array([[ 0.14801842, -1.04885222,  0.30115562],
       [ 1.25363111, -0.00905462,  1.69179347],
       [ 0.02763855,  1.12558686,  0.63470486],
       [ 0.98348503,  0.        , -0.77570324],
       [ 0.94334509,  1.02527599,  2.11085678],
       [ 0.22322905,  0.        ,  0.56210592],
       [-1.52242446,  0.        , -0.51971829]])

In [67]:
x_train, x_test, y_train, y_test = train_test_split(previsores, classe, test_size=0.25, random_state=0)

classificador = GaussianNB()
classificador.fit(x_train, y_train)
previsoes = classificador.predict(x_test)
previsoes

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [68]:
precisao = accuracy_score(y_test, previsoes)
matriz = confusion_matrix(y_test, previsoes)
precisao

0.938

In [69]:
matriz

array([[428,   8],
       [ 23,  41]])